### ISSUE TITLE
GripQL docs need to be updated

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-site#11]
Most recent release of GripQL has changed some of the methods, docs need to be updated:
 - [ ] content/queries/traversal.md
 - [ ] content/queries/matrix.md
 - [ ] content/queries/kaplan_meier.md
 - [ ] content/queries/drug_response.md
 - [ ] content/queries/getting_started.md
 - [ ] content/queries/install.md (need pip install from PyPi)

**Comment by adamstruck** [comment]
The following paths need to be updated: 
- [ ] /queries/getting_started
- [ ] /queries/traversal

The content on these pages is the same as:
 - https://docs.bmeg.io/grip/docs/queries/getting_started
 - https://docs.bmeg.io/grip/docs/queries/operations

Maybe the main BMEG site should just link out to these existing pages.
