### ISSUE TITLE
Label version on Graph Schema Page

### ISSUE THREAD

**Issue by Mekdes-cyber** [bmeg/bmeg-site#43]
I have noticed that the Schema version changes periodically. And when I was trying to run a code that used an older schema version, it didn't work. I am building a tutorial and I really think it would be useful if people can tell what schema version is used in a specific code and know what version is the new schema on the BMEG site. To avoid confusion and to make things easier for a user, I suggest we label each new Schema that is posted on the schema page. You can label it version 1, version 2, or simply put the schema name like rc_2.

**Comment by adamstruck** [comment]
schema selection added in #47
